name: River Plate Ticket Checker

on:
  schedule:
    - cron: "0 */12 * * *" # Cada 12 horas (a la hora 0 y 12 UTC)
  workflow_dispatch: # Permite correrlo manualmente desde GitHub
  push:
    branches:
      - main

env:
  EMAIL_USER: ${{ secrets.EMAIL_USER }}
  EMAIL_PASS: ${{ secrets.EMAIL_PASS }}

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script
        run: python src/main.py

      - name: Auto-commit si hubo cambios
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update last match
          commit_user_name: GitHub Action
          commit_user_email: action@github.com
          file_pattern: last_match.txt
